<a href="https://colab.research.google.com/github/2303A51763/2303A51763-PYTHON-DATASCIENCE/blob/main/Lab_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = np.array([
    [85, 78, 92],
    [66, 74, 58],
    [90, 88, 95],
    [45, 56, 60],
    [72, 81, 77]
])

print("Student Marks:\n", marks)

avg_marks = np.mean(marks, axis=1)
min_marks = np.min(marks)
max_marks = np.max(marks)

print("\nAverage Marks of each student:", avg_marks)
print("Minimum Mark in the class:", min_marks)
print("Maximum Mark in the class:", max_marks)


print("\nMarks of first 3 students:\n", marks[:3])

above_80 = marks[marks > 80]
print("\nMarks greater than 80:", above_80)

reshaped = marks.T
print("\nSubject-wise Performance (rows=subjects, cols=students):\n", reshaped)


Student Marks:
 [[85 78 92]
 [66 74 58]
 [90 88 95]
 [45 56 60]
 [72 81 77]]

Average Marks of each student: [85.         66.         91.         53.66666667 76.66666667]
Minimum Mark in the class: 45
Maximum Mark in the class: 95

Marks of first 3 students:
 [[85 78 92]
 [66 74 58]
 [90 88 95]]

Marks greater than 80: [85 92 90 88 95 81]

Subject-wise Performance (rows=subjects, cols=students):
 [[85 66 90 45 72]
 [78 74 88 56 81]
 [92 58 95 60 77]]
