<a href="https://colab.research.google.com/github/2303A51763/2303A51763-PYTHON-DATASCIENCE/blob/main/LAB_3_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

a = np.array([[78, 85, 90, 92],
              [88, 76, 95, 89],
              [92, 91, 85, 87],
              [75, 80, 79, 83]])

print("Array:\n", a)

print("Row wise mean =", np.mean(a, axis=1))
print("Column wise mean =", np.mean(a, axis=0))

print("Standard Deviation =", np.std(a))
print("Variance =", np.var(a))

print("Minimum value =", np.min(a), "at index", np.unravel_index(np.argmin(a), a.shape))
print("Maximum value =", np.max(a), "at index", np.unravel_index(np.argmax(a), a.shape))


Array:
 [[78 85 90 92]
 [88 76 95 89]
 [92 91 85 87]
 [75 80 79 83]]
Row wise mean = [86.25 87.   88.75 79.25]
Column wise mean = [83.25 83.   87.25 87.75]
Standard Deviation = 6.028253789448484
Variance = 36.33984375
Minimum value = 75 at index (np.int64(3), np.int64(0))
Maximum value = 95 at index (np.int64(1), np.int64(2))
